In [212]:
import pandas as pd

In [213]:
membership_df = pd.read_csv('./../data/christmas_cup_2024/members-list.csv')
membership_df

,ID,username,email,name,first_name,last_name,txn_count,active_txn_count,expired_txn_count,trial_txn_count,...,registered,mepr-address-one,mepr-address-two,mepr-address-city,mepr-address-country,mepr-address-state,mepr-address-zip,mepr_create_your_membership_id_must_include_your_initials_and_4_digits,mepr_phone_number,_mepr_stripe_customer_id_rt35lr-4mr_AUD
0,8955,_beckz002,leah.becks11@gmail.com,"Beckenham, Leah",Leah,Beckenham,1,1,0,0,...,2023-11-17 03:32:55,13-21 Old Greenbank Rd,NaN,Greenbank,AU,QLD,4124,LB2103,NaN,cus_P1LUJYkgHx9jGy
1,9308,_jessmaree,jess.maree1204@yahoo.com,"Hall, Jessica",Jessica,Hall,1,1,0,0,...,2024-02-04 08:17:00,3 Adam street Blackalls Park,NaN,Blackalls Park,AU,NSW,2283,JH1204,NaN,cus_PV0uI4rkL9svLp
2,8497,_nicoleshore,nicole.shore@hotmail.com,"Shore, Nicole",Nicole,Shore,1,0,1,0,...,2023-08-03 00:39:35,228 Fawcett Road,NaN,Waroona,AU,WA,6215,NS2508,436305895,cus_ONaloSbUVKZVPF
3,9322,123Lexley01,123lexley01@gmail.com,"Exley, Luke",Luke,Exley,1,1,0,0,...,2024-02-06 23:44:05,63 Power Street,NaN,Norman Park,AU,QLD,4170,LE1305,0490763386,cus_PW0JO81EcFNiw0
4,10189,13irdau,Jcamp03@icloud.com,"Campbell, Joshua",Joshua,Campbell,1,1,0,0,...,2024-08-21 03:59:14,14/78 Brookfield road,Kenmore hills,Brisbane,AU,QLD,4069,JoshC2003,+61436642711,cus_QhUgc65IsinKLR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1669,8930,Zilzie,zilzie.f@gmail.com,"Ferguson, Zilzie",Zilzie,Ferguson,1,1,0,0,...,2023-11-16 03:23:50,NaN,NaN,NaN,NaN,NaN,NaN,ZF2501,NaN,NaN
1670,9859,Zinny,mjblackwood1980@hotmail.com,"Blackwood, Michael",Michael,Blackwood,1,1,0,0,...,2024-05-29 04:45:53,Unit 1007 / 125 Grafton St,NaN,Cairns,AU,QLD,4870,MB3012,+61487390177,cus_QC2TVzJejbqlVz
1671,9851,ZJY0538,angusmr.zhang@gmail.com,"Zhang, Jiyou",Jiyou,Zhang,1,1,0,0,...,2024-05-24 12:33:29,unit 205a/1095 Plenty Road,NaN,Bundoora,AU,VIC,3083,ZJY0538,+61426453930,cus_QAHt3c0XjVZECi
1672,10155,Zo_Kruger,zokruger@gmail.com,"Kruger, Zo",Zo,Kruger,1,1,0,0,...,2024-08-13 00:13:41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1673,9952,Zsultana.09,zsultana.09@gmail.com,"Sultana, Zachary",Zachary,Sultana,1,1,0,0,...,2024-06-28 04:36:20,18 Whitehaven Crescent,NaN,Woolgoolga,AU,NSW,2456,Zs2000,+61478452698,cus_QNH6K4Wi9vlAJa

In [214]:
df = pd.read_csv('./../data/open-powerlifting-australia.csv', low_memory=False)
df

,Name,Sex,Event,Equipment,Age,AgeClass,BirthYearClass,Division,BodyweightKg,WeightClassKg,...,Country,State,Federation,ParentFederation,Date,MeetCountry,MeetState,MeetTown,MeetName,Sanctioned
0,E.S. Denisenko,F,B,Raw,28.5,24-34,24-39,Open,67.3,NaN,...,NaN,NaN,GSF-Belarus,NaN,2019-06-22,Belarus,NaN,Luninets,Bison Power Cup,Yes
1,I.S. Lebetskaya,F,B,Raw,43.5,40-44,40-49,Open,73.2,NaN,...,NaN,NaN,GSF-Belarus,NaN,2019-06-22,Belarus,NaN,Luninets,Bison Power Cup,Yes
2,K. Yakimovich,F,B,Raw,26.5,24-34,24-39,Open,60.6,NaN,...,NaN,NaN,GSF-Belarus,NaN,2019-06-22,Belarus,NaN,Luninets,Bison Power Cup,Yes
3,A.G. Golneva,F,B,Raw,19.5,20-23,19-23,Juniors 17-21,50.3,NaN,...,NaN,NaN,GSF-Belarus,NaN,2019-06-22,Belarus,NaN,Luninets,Bison Power Cup,Yes
4,E.V. Marunevskaya,F,B,Raw,19.5,20-23,19-23,Juniors 17-21,63.7,NaN,...,NaN,NaN,GSF-Belarus,NaN,2019-06-22,Belarus,NaN,Luninets,Bison Power Cup,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3267070,Ibrahim Sandogji,M,SBD,Raw,17.0,16-17,14-18,Sub-Juniors,64.4,66,...,Saudi Arabia,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes
3267071,Feras Alwahhabi,M,SBD,Raw,17.0,16-17,14-18,Sub-Juniors,82.9,83,...,Saudi Arabia,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes
3267072,Musab Alessa,M,SBD,Raw,17.0,16-17,14-18,Sub-Juniors,91.3,93,...,Saudi Arabia,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes
3267073,Ali Alholan,M,SBD,Raw,18.0,18-19,14-18,Sub-Juniors,103.6,105,...,NaN,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes
3267074,Alfarooq Eissa,M,SBD,Raw,18.0,18-19,14-18,Sub-Juniors,157.3,120+,...,NaN,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes

In [215]:
filtered_df = df[df['Date'] >= '2023-09-01']
filtered_df.head()

,Name,Sex,Event,Equipment,Age,AgeClass,BirthYearClass,Division,BodyweightKg,WeightClassKg,...,Country,State,Federation,ParentFederation,Date,MeetCountry,MeetState,MeetTown,MeetName,Sanctioned
21002,陈芳,F,SBD,Raw,NaN,NaN,NaN,Open,NaN,NaN,...,China,NaN,WP-China,WP,2024-07-14,China,SC,Chengdu,DiamondStrength Meet,Yes
21003,周頔娜,F,SBD,Raw,NaN,NaN,NaN,Open,51.55,53,...,NaN,NaN,WP-China,WP,2024-07-14,China,SC,Chengdu,DiamondStrength Meet,Yes
21004,顾奖逸,F,SBD,Raw,NaN,NaN,NaN,Open,52.05,53,...,NaN,NaN,WP-China,WP,2024-07-14,China,SC,Chengdu,DiamondStrength Meet,Yes
21005,焦琳,F,SBD,Raw,NaN,NaN,NaN,Open,55.55,58,...,NaN,NaN,WP-China,WP,2024-07-14,China,SC,Chengdu,DiamondStrength Meet,Yes
21006,廖丽,F,SBD,Raw,NaN,NaN,NaN,Open,57.35,58,...,NaN,NaN,WP-China,WP,2024-07-14,China,SC,Chengdu,DiamondStrength Meet,Yes

In [216]:
filtered_df = filtered_df[filtered_df['Federation'] == 'AusPL'].drop_duplicates('Name')
filtered_df

,Name,Sex,Event,Equipment,Age,AgeClass,BirthYearClass,Division,BodyweightKg,WeightClassKg,...,Country,State,Federation,ParentFederation,Date,MeetCountry,MeetState,MeetTown,MeetName,Sanctioned
338836,Chelsea Fraser,F,SBD,Raw,24.0,24-34,24-39,Open,65.50,67.5,...,NaN,NaN,AusPL,NaN,2024-05-18,Australia,QLD,Cairns,Backyard Battle Drug Tested,Yes
338837,Eev Rose Braithwaite-Girle,F,SBD,Raw,21.0,20-23,19-23,Open,67.10,67.5,...,NaN,NaN,AusPL,NaN,2024-05-18,Australia,QLD,Cairns,Backyard Battle Drug Tested,Yes
338838,Michelle Resende Castelani,F,SBD,Raw,40.0,40-44,40-49,Open,70.80,75,...,NaN,NaN,AusPL,NaN,2024-05-18,Australia,QLD,Cairns,Backyard Battle Drug Tested,Yes
338839,Taylah Steinhofer,F,SBD,Raw,18.0,18-19,14-18,Open,70.00,75,...,NaN,NaN,AusPL,NaN,2024-05-18,Australia,QLD,Cairns,Backyard Battle Drug Tested,Yes
338840,Virginia King,F,SBD,Raw,37.0,35-39,24-39,Open,81.80,82.5,...,NaN,NaN,AusPL,NaN,2024-05-18,Australia,QLD,Cairns,Backyard Battle Drug Tested,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344045,Lewis Coull,M,SBD,Raw,20.0,20-23,19-23,Open,87.50,90,...,Australia,NaN,AusPL,NaN,2023-11-25,Australia,TAS,Devonport,Northern Classic Tested,Yes
344046,Louis Horstmann,M,SBD,Raw,26.0,24-34,24-39,Open,86.40,90,...,Australia,NaN,AusPL,NaN,2023-11-25,Australia,TAS,Devonport,Northern Classic Tested,Yes
344047,Justin Nobes,M,SBD,Wraps,35.0,35-39,24-39,Open,79.30,82.5,...,NaN,NaN,AusPL,NaN,2023-11-25,Australia,TAS,Devonport,Northern Classic Tested,Yes
344048,Matto Vucetic,M,SBD,Wraps,33.0,24-34,24-39,Open,109.95,110,...,NaN,NaN,AusPL,NaN,2023-11-25,Australia,TAS,Devonport,Northern Classic Tested,Yes
344049,Jack Nelson,M,BD,Raw,18.0,18-19,NaN,Open,85.20,90,...,USA,NaN,AusPL,NaN,2023-11-25,Australia,TAS,Devonport,Northern Classic Tested,Yes

In [217]:
df_male = filtered_df[filtered_df['Sex'] == 'M']
df_female = filtered_df[filtered_df['Sex'] == 'F']

In [218]:
df_male_filtered = df_male[df_male['Dots'] >= 400]
df_female_filtered = df_female[df_female['Dots'] >= 340]

In [219]:
df_female_filtered

,Name,Sex,Event,Equipment,Age,AgeClass,BirthYearClass,Division,BodyweightKg,WeightClassKg,...,Country,State,Federation,ParentFederation,Date,MeetCountry,MeetState,MeetTown,MeetName,Sanctioned
338843,Rubena Uelese,F,SBD,Raw,38.0,35-39,24-39,Open,107.00,110,...,NaN,NaN,AusPL,NaN,2024-05-18,Australia,QLD,Cairns,Backyard Battle Drug Tested,Yes
339241,Lynsey Barr,F,SBD,Wraps,40.0,40-44,40-49,Open,78.36,82.5,...,Australia,NaN,AusPL,NaN,2024-03-09,Australia,NSW,Brookvale,Summer Send Off Open,Yes
339270,Carmen Daldry,F,SBD,Raw,40.0,40-44,40-49,M40-49,74.10,75,...,Australia,NaN,AusPL,NaN,2024-08-04,Australia,VIC,Lilydale,Strength HQ Winter Cup,Yes
339274,Caitlin Fleming,F,SBD,Wraps,29.0,24-34,24-39,Open,64.50,67.5,...,Australia,NaN,AusPL,NaN,2024-08-04,Australia,VIC,Lilydale,Strength HQ Winter Cup,Yes
339275,Tiffaney Cole,F,SBD,Raw,28.0,24-34,24-39,Open,67.50,67.5,...,Australia,NaN,AusPL,NaN,2024-08-04,Australia,VIC,Lilydale,Strength HQ Winter Cup,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343589,Jaime Canton,F,SBD,Wraps,32.0,24-34,24-39,Open,81.30,NaN,...,New Zealand,NaN,AusPL,NaN,2024-05-25,New Zealand,NaN,Tauranga,Ruthless Classic,Yes
343884,Stacey Nowlan,F,SBD,Raw,31.0,24-34,24-39,Open,59.50,60,...,NaN,NaN,AusPL,NaN,2023-09-02,Australia,QLD,Townsville,Townsville Cup Drug Tested,Yes
343889,Jacqueline Feher,F,SBD,Raw,40.0,40-44,40-49,Open,74.10,75,...,NaN,NaN,AusPL,NaN,2023-09-02,Australia,QLD,Townsville,Townsville Cup Drug Tested,Yes
343890,Briana Letta,F,SBD,Raw,24.0,24-34,24-39,Open,72.50,75,...,NaN,NaN,AusPL,NaN,2023-09-02,Australia,QLD,Townsville,Townsville Cup Drug Tested,Yes
343895,Bridget Luina Hughes,F,SBD,Wraps,32.0,24-34,24-39,Open,71.90,75,...,NaN,NaN,AusPL,NaN,2023-09-02,Australia,QLD,Townsville,Townsville Cup Drug Tested,Yes

In [220]:
df_male_filtered

,Name,Sex,Event,Equipment,Age,AgeClass,BirthYearClass,Division,BodyweightKg,WeightClassKg,...,Country,State,Federation,ParentFederation,Date,MeetCountry,MeetState,MeetTown,MeetName,Sanctioned
338845,Leander Andersen,M,SBD,Wraps,36.0,35-39,24-39,Open,105.10,110,...,NaN,NaN,AusPL,NaN,2024-05-18,Australia,QLD,Cairns,Backyard Battle Drug Tested,Yes
339231,Jordan Mang,M,SBD,Raw,32.0,24-34,24-39,Open,81.20,82.5,...,NaN,NaN,AusPL,NaN,2024-03-09,Australia,QLD,Cairns,Cairns Cup Open,Yes
339232,Matthew Cheesman,M,SBD,Raw,23.0,20-23,24-39,Open,89.60,90,...,Australia,NaN,AusPL,NaN,2024-03-09,Australia,QLD,Cairns,Cairns Cup Open,Yes
339236,Jacob Danielsen-Jensen,M,SBD,Wraps,25.0,24-34,24-39,Open,123.40,125,...,NaN,NaN,AusPL,NaN,2024-03-09,Australia,QLD,Cairns,Cairns Cup Open,Yes
339237,Luke Hare,M,SBD,Wraps,29.0,24-34,24-39,Open,123.60,125,...,Australia,NaN,AusPL,NaN,2024-03-09,Australia,QLD,Cairns,Cairns Cup Open,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343902,Regan Payne,M,SBD,Raw,23.0,20-23,NaN,Open,77.70,82.5,...,Australia,NaN,AusPL,NaN,2023-09-02,Australia,QLD,Townsville,Townsville Cup Drug Tested,Yes
343911,Kent Nielsen,M,SBD,Raw,19.0,18-19,19-23,Open,141.80,140+,...,NaN,NaN,AusPL,NaN,2023-09-02,Australia,QLD,Townsville,Townsville Cup Drug Tested,Yes
343913,Junille Mendoza,M,SBD,Wraps,26.0,24-34,24-39,Open,64.40,67.5,...,NaN,NaN,AusPL,NaN,2023-09-02,Australia,QLD,Townsville,Townsville Cup Drug Tested,Yes
343917,Aaron Fontana,M,SBD,Wraps,22.0,20-23,19-23,Open,93.90,100,...,Australia,NaN,AusPL,NaN,2023-09-02,Australia,QLD,Townsville,Townsville Cup Drug Tested,Yes
344048,Matto Vucetic,M,SBD,Wraps,33.0,24-34,24-39,Open,109.95,110,...,NaN,NaN,AusPL,NaN,2023-11-25,Australia,TAS,Devonport,Northern Classic Tested,Yes

In [221]:
# Create a new Excel file and write the DataFrames to separate sheets
with pd.ExcelWriter('christmas_cup.xlsx', engine='xlsxwriter') as writer:
    filtered_df.to_excel(writer, sheet_name='all_lifters', index=False)
    df_male_filtered.to_excel(writer, sheet_name='male', index=False)
    df_female_filtered.to_excel(writer, sheet_name='female', index=False)