In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('cairns.csv')
df

,AGREED_DATE,START_DATE,TYPE,STATUS,METHOD,MERCHANT,CUSTOMER,REFERENCE,PAYMENT_REQUEST,NEXT_PAYMENT,NEXT_PAYMENT_ON,LAST_PAYMENT,LAST_PAYMENT_ON,CANCEL_DATE,COMMENCEMENT_DATE,COMPLETION_DATE,TOTAL_VALUE,PAID,REMAINING,AGREEMENT_ID
0,2023-01-02,2023-01-18,Fixed,Complete,Mastercard,ZeroW Cairns PTY LTD,Rebecca Meyer,NaN,kbzbofm9lank,0.0,NaN,28.0,2023-04-05,NaN,2023-01-18,2023-04-05,336.0,336.0,0.0,91629f88-960f-4f7c-9613-fbf80e62238b
1,2023-01-02,2023-01-18,Fixed,Complete,Mastercard,ZeroW Cairns PTY LTD,Maria Grimaldi,NaN,xid7wdy0nmwn,0.0,NaN,28.0,2023-04-05,NaN,2023-01-18,2023-04-05,336.0,336.0,0.0,6b635e3d-e1dd-4fed-a51c-05faaabae5f5
2,2023-01-02,2023-01-16,Fixed,Complete,Mastercard,ZeroW Cairns PTY LTD,Marc Rogers,NaN,787mutujzbwe,0.0,NaN,28.0,2023-04-05,NaN,2023-01-18,2023-04-05,336.0,336.0,0.0,a4950a2a-bb4f-48a6-8258-274a60d4f1a6
3,2023-01-02,2023-01-16,Fixed,Cancelled,Visa,ZeroW Cairns PTY LTD,Kelsea Taylor,NaN,qx7u6ez29vic,0.0,NaN,56.0,2023-03-30,2023-04-11,2023-01-19,2023-03-30,336.0,336.0,0.0,762e50b7-efe6-4f15-877d-4fc0bfac9f41
4,2023-01-02,2023-01-16,Fixed,Complete,Mastercard,ZeroW Cairns PTY LTD,Kayla McLeish,NaN,0ax1l1hugb9l,0.0,NaN,28.0,2023-04-05,NaN,2023-01-18,2023-04-05,336.0,336.0,0.0,25d5f75c-2b87-460e-9a51-68e02675bbdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486,2024-08-03,2024-08-03,Recurring,Active,Visa,ZeroW Cairns PTY LTD,Skye Mitchell,NaN,ejG3EvKKHUwYsi,35.0,2024-08-21,35.0,2024-08-09,NaN,2024-08-09,2025-01-08,420.0,35.0,385.0,77345e28-5073-11ef-896e-c2f3c5f96960
487,2024-08-06,2024-08-15,Recurring,In Transit,Visa,ZeroW Cairns PTY LTD,Frank Richter-Smith,NaN,ivi3qEbNpczoMV,35.0,2024-08-21,0.0,NaN,NaN,2024-08-21,2025-01-22,420.0,0.0,420.0,2a81fba8-5073-11ef-9de6-5a41d36501c6
488,2024-08-13,2024-08-13,Recurring,Active,Mastercard,ZeroW Cairns PTY LTD,Thiago Montenegro Caram,NaN,Z2ZRDty1Cc1kGB,35.0,2024-08-21,35.0,2024-08-14,NaN,2024-08-13,2024-10-30,420.0,35.0,385.0,36e406f0-5944-11ef-8ef9-5e2abea2232b
489,2024-08-14,2024-08-14,Recurring,Active,Visa,ZeroW Cairns PTY LTD,Leo Case,NaN,tC0xlKtJzFKXZt,35.0,2024-08-21,35.0,2024-08-14,NaN,2024-08-14,2024-10-30,420.0,35.0,385.0,842d837e-59d9-11ef-bc38-5e2abea2232b
490,2024-08-18,2024-08-26,Recurring,In Transit,Mastercard,ZeroW Cairns PTY LTD,Gavin Harris,NaN,D5UJ2vCCkFjngv,99.0,2024-08-28,0.0,NaN,NaN,2024-08-28,2025-01-29,1188.0,0.0,1188.0,53403c2c-5b76-11ef-87de-16edd30aad39

In [3]:
filtered_df = df[~df['STATUS'].isin(['Cancelled', 'Paused'])]
filtered_df

,AGREED_DATE,START_DATE,TYPE,STATUS,METHOD,MERCHANT,CUSTOMER,REFERENCE,PAYMENT_REQUEST,NEXT_PAYMENT,NEXT_PAYMENT_ON,LAST_PAYMENT,LAST_PAYMENT_ON,CANCEL_DATE,COMMENCEMENT_DATE,COMPLETION_DATE,TOTAL_VALUE,PAID,REMAINING,AGREEMENT_ID
0,2023-01-02,2023-01-18,Fixed,Complete,Mastercard,ZeroW Cairns PTY LTD,Rebecca Meyer,NaN,kbzbofm9lank,0.0,NaN,28.0,2023-04-05,NaN,2023-01-18,2023-04-05,336.0,336.0,0.0,91629f88-960f-4f7c-9613-fbf80e62238b
1,2023-01-02,2023-01-18,Fixed,Complete,Mastercard,ZeroW Cairns PTY LTD,Maria Grimaldi,NaN,xid7wdy0nmwn,0.0,NaN,28.0,2023-04-05,NaN,2023-01-18,2023-04-05,336.0,336.0,0.0,6b635e3d-e1dd-4fed-a51c-05faaabae5f5
2,2023-01-02,2023-01-16,Fixed,Complete,Mastercard,ZeroW Cairns PTY LTD,Marc Rogers,NaN,787mutujzbwe,0.0,NaN,28.0,2023-04-05,NaN,2023-01-18,2023-04-05,336.0,336.0,0.0,a4950a2a-bb4f-48a6-8258-274a60d4f1a6
4,2023-01-02,2023-01-16,Fixed,Complete,Mastercard,ZeroW Cairns PTY LTD,Kayla McLeish,NaN,0ax1l1hugb9l,0.0,NaN,28.0,2023-04-05,NaN,2023-01-18,2023-04-05,336.0,336.0,0.0,25d5f75c-2b87-460e-9a51-68e02675bbdf
6,2023-01-02,2023-01-16,Fixed,Complete,Mastercard,ZeroW Cairns PTY LTD,Merenia Waaka,NaN,elmmlzhnuos6,0.0,NaN,28.0,2023-04-05,NaN,2023-01-18,2023-04-05,336.0,336.0,0.0,09fd9087-01f0-431b-9971-bdcc169e4c41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486,2024-08-03,2024-08-03,Recurring,Active,Visa,ZeroW Cairns PTY LTD,Skye Mitchell,NaN,ejG3EvKKHUwYsi,35.0,2024-08-21,35.0,2024-08-09,NaN,2024-08-09,2025-01-08,420.0,35.0,385.0,77345e28-5073-11ef-896e-c2f3c5f96960
487,2024-08-06,2024-08-15,Recurring,In Transit,Visa,ZeroW Cairns PTY LTD,Frank Richter-Smith,NaN,ivi3qEbNpczoMV,35.0,2024-08-21,0.0,NaN,NaN,2024-08-21,2025-01-22,420.0,0.0,420.0,2a81fba8-5073-11ef-9de6-5a41d36501c6
488,2024-08-13,2024-08-13,Recurring,Active,Mastercard,ZeroW Cairns PTY LTD,Thiago Montenegro Caram,NaN,Z2ZRDty1Cc1kGB,35.0,2024-08-21,35.0,2024-08-14,NaN,2024-08-13,2024-10-30,420.0,35.0,385.0,36e406f0-5944-11ef-8ef9-5e2abea2232b
489,2024-08-14,2024-08-14,Recurring,Active,Visa,ZeroW Cairns PTY LTD,Leo Case,NaN,tC0xlKtJzFKXZt,35.0,2024-08-21,35.0,2024-08-14,NaN,2024-08-14,2024-10-30,420.0,35.0,385.0,842d837e-59d9-11ef-bc38-5e2abea2232b
490,2024-08-18,2024-08-26,Recurring,In Transit,Mastercard,ZeroW Cairns PTY LTD,Gavin Harris,NaN,D5UJ2vCCkFjngv,99.0,2024-08-28,0.0,NaN,NaN,2024-08-28,2025-01-29,1188.0,0.0,1188.0,53403c2c-5b76-11ef-87de-16edd30aad39

In [4]:
result_df = filtered_df.groupby('CUSTOMER')[['NEXT_PAYMENT', 'LAST_PAYMENT', 'TOTAL_VALUE', 'PAID', 'REMAINING']].sum()
result_df

,NEXT_PAYMENT,LAST_PAYMENT,TOTAL_VALUE,PAID,REMAINING
CUSTOMER,,,,,
Aidan Day,35.0,63.0,3101.0,2716.0,385.0
Aimee Pike,99.0,99.0,1386.0,297.0,1089.0
Akiko Bourchier,35.0,35.0,595.0,105.0,490.0
Albert O'Shannessy,0.0,28.0,336.0,336.0,0.0
Amelia Rose Hughes,0.0,20.0,240.0,240.0,0.0
...,...,...,...,...,...
Tennille Falappi,35.0,35.0,560.0,175.0,385.0
Thiago Montenegro Caram,35.0,35.0,420.0,35.0,385.0
Vanessa Hoedlmayr,0.0,28.0,336.0,336.0,0.0
Vera Normington,67.0,120.6,6137.2,5467.2,670.0
Vicki Pates,30.0,30.0,2400.0,2070.0,330.0

In [5]:
result_df.index.nunique()

180