In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('gold_coast.csv')
df

,customer_name,customer_email,phoneNumber,plan.interval,created,current_period_start,status
0,Sailor Boonkan,sailor0ak@icloud.com,61403506008,Standard Memberhip,"Aug 12, 2024","Aug 12, 2024",active
1,Bailey Wilton,baileyalford0831@gmail.com,61487040625,Standard Memberhip,"Aug 9, 2024","Aug 16, 2024",active
2,Liam Byrne,liamgbyrne@hotmail.com,61459348864,Gold,"Aug 5, 2024","Aug 12, 2024",past_due
3,Jason Cooke,jas_cooke@hotmail.com,61407222321,Standard Memberhip,"Aug 2, 2024","Aug 16, 2024",active
4,Joshua Burridge,untappedoutput@gmail.com,61417761424,Standard Memberhip,"Aug 1, 2024","Aug 15, 2024",active
...,...,...,...,...,...,...,...
171,Jude Rusga,juderusgayt@gmail.com,61488673911,Standard Memberhip,"Dec 12, 2023","Dec 26, 2023",canceled
172,Bridget Murphy,gidge1986@gmail.com,61411359946,Standard Memberhip,"Dec 12, 2023","Aug 13, 2024",active
173,Bri Bradfield,offseasoncoachlb@gmail.com,61447153068,Standard Memberhip,"Dec 12, 2023","Mar 5, 2024",canceled
174,Liam Kinzett,liamkinz@hotmail.com,61424569523,Standard Memberhip,"Dec 12, 2023","Mar 5, 2024",canceled
175,James Hendry,james@zerow.com.au,61451664335,Standard Memberhip,"Dec 12, 2023","Aug 13, 2024",active

In [3]:
filtered_df = df[~df['status'].isin(['canceled', 'paused'])]
filtered_df

,customer_name,customer_email,phoneNumber,plan.interval,created,current_period_start,status
0,Sailor Boonkan,sailor0ak@icloud.com,61403506008,Standard Memberhip,"Aug 12, 2024","Aug 12, 2024",active
1,Bailey Wilton,baileyalford0831@gmail.com,61487040625,Standard Memberhip,"Aug 9, 2024","Aug 16, 2024",active
2,Liam Byrne,liamgbyrne@hotmail.com,61459348864,Gold,"Aug 5, 2024","Aug 12, 2024",past_due
3,Jason Cooke,jas_cooke@hotmail.com,61407222321,Standard Memberhip,"Aug 2, 2024","Aug 16, 2024",active
4,Joshua Burridge,untappedoutput@gmail.com,61417761424,Standard Memberhip,"Aug 1, 2024","Aug 15, 2024",active
...,...,...,...,...,...,...,...
165,Josh Dawson,josh6dawson@gmail.com,61433061510,Standard Memberhip,"Dec 13, 2023","Aug 14, 2024",active
169,Hudson Schultz,hudsoncschultz@gmail.com,61459390163,Standard Memberhip,"Dec 13, 2023","Aug 14, 2024",active
170,Troy Schultz,troydschultz@gmail.com,61474824332,Standard Memberhip,"Dec 13, 2023","Aug 14, 2024",active
172,Bridget Murphy,gidge1986@gmail.com,61411359946,Standard Memberhip,"Dec 12, 2023","Aug 13, 2024",active
175,James Hendry,james@zerow.com.au,61451664335,Standard Memberhip,"Dec 12, 2023","Aug 13, 2024",active

In [4]:
result_df = filtered_df.groupby('customer_name').sum()
result_df

,customer_email,phoneNumber,plan.interval,created,current_period_start,status
customer_name,,,,,,
Aaron Kuczynski,kuczynski.aaron@gmail.com,61476197927,Standard Memberhip,"Dec 22, 2023","Aug 16, 2024",active
Adam Bolton,adam.bolton@boltonfs.com.au,61433325382,Gold,"Jan 15, 2024","Aug 12, 2024",active
Adam Lam,adamklam@gmail.com,61404894918,Standard Memberhip,"Dec 21, 2023","Aug 15, 2024",active
Alesha S,aleshajstagg@gmail.com,61412666109,Standard Memberhip,"Jun 11, 2024","Aug 13, 2024",active
Alessandra Perry,ali.m.perry@gmail.com,61402847212,Standard Memberhip,"Jun 25, 2024","Aug 13, 2024",active
...,...,...,...,...,...,...
Troy Schultz,troydschultz@gmail.com,61474824332,Standard Memberhip,"Dec 13, 2023","Aug 14, 2024",active
Vincent Takataka,vincenttakataka316@gmail.com,61433933153,Standard Memberhip,"Jan 16, 2024","Aug 13, 2024",active
Will Koskela,willkoskela97@gmail.com,61449929177,Standard Memberhip,"Dec 27, 2023","Aug 14, 2024",active
Youre Awesome Matilde Newman,mindstertraining@gmail.com,61478044494,Silver,"Dec 27, 2023","Aug 14, 2024",active
Zion Hawes,zionhawes@hotmail.com,61434933919,Standard Memberhip,"Apr 4, 2024","Aug 15, 2024",active

In [5]:
result_df.index.nunique()

114