In [5]:
import pandas as pd

In [6]:
file_path = './../data/paypa_plane/ZeroW_Brisbane-Agreements-2024-06-21.csv'

In [7]:
df = pd.read_csv(file_path)
df

,AGREED_DATE,START_DATE,TYPE,STATUS,METHOD,CUSTOMER,REFERENCE,PAYMENT_REQUEST,NEXT_PAYMENT,NEXT_PAYMENT_ON,LAST_PAYMENT,LAST_PAYMENT_ON,CANCEL_DATE,COMMENCEMENT_DATE,COMPLETION_DATE,TOTAL_VALUE,PAID,REMAINING,AGREEMENT_ID
0,2022-04-19,2022-04-22,Recurring,Cancelled,Visa,Rin Dwyer,NaN,f96ped5g25ds,0.0,NaN,79.0,2022-07-29,2022-07-30,2022-04-22,2022-07-29,1185.00,1185.00,0.0,6a0ab7cb-32b4-4c3b-9592-adad7295e9eb
1,2022-04-19,2022-04-20,Recurring,Cancelled,Mastercard,Sophia Fisher,NaN,86krl6ylpx17,0.0,NaN,28.0,2022-05-04,2022-05-08,2022-04-20,2022-05-04,84.00,84.00,0.0,114f42ca-83c5-4856-b3e1-9002cef168ea
2,2022-04-19,2022-04-20,Recurring,Active,Visa,Michael Wawrzyniak,NaN,qcot98d2a4mg,220.0,2024-07-26,220.0,2024-07-19,NaN,2022-04-22,2024-10-04,28183.75,25763.75,2420.0,011bf6a4-7a39-46a6-8302-ee884114950c
3,2022-04-20,2022-04-21,Recurring,Cancelled,Mastercard,Declan McMenz,NaN,u9man5uyxb1v,0.0,NaN,28.0,2022-07-28,2022-07-29,2022-04-21,2022-07-28,364.00,364.00,0.0,4940733b-e70a-480d-b998-45270d976958
4,2022-04-20,2022-04-21,Recurring,Cancelled,Visa,Elisha Low,NaN,1b11aveotrax,0.0,NaN,28.0,2022-07-28,2022-07-29,2022-04-21,2022-07-28,420.00,420.00,0.0,1b5f66cf-7c16-44b1-9e85-fa0917031f77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,2024-07-08,2024-07-08,Recurring,Active,Visa,Beth Perry,NaN,8n4XvfZ5Mz9QPa,35.0,2024-07-24,35.0,2024-07-17,NaN,2024-07-08,2024-10-02,455.00,70.00,385.0,1239d43e-3cbf-11ef-9499-967b370f99ea
306,2024-07-11,2024-07-09,Recurring,Active,Visa,Josh Wright,NaN,rkXqPiJsLTrSKc,35.0,2024-07-23,35.0,2024-07-16,NaN,2024-07-09,2024-10-01,455.00,70.00,385.0,05287186-3dc0-11ef-9b56-8620f1aa2c76
307,2024-07-12,2024-07-12,Recurring,Active,Mastercard,Kiel Woodward,NaN,2fV9ytFfRslJlb,99.0,2024-07-26,99.0,2024-07-12,NaN,2024-07-12,2024-12-13,1188.00,99.00,1089.0,d9112374-3f57-11ef-9e56-96d25c3b9f01
308,2024-07-16,2024-07-22,Recurring,In Transit,Visa,Bill Morrissey,NaN,nFypt6apxQr66f,35.0,2024-07-22,0.0,NaN,NaN,2024-07-22,2024-10-07,420.00,0.00,420.0,ba07ecde-4302-11ef-af32-4ebdaad81281
309,2024-07-19,2024-07-05,Recurring,Active,Mastercard,Usukhbayar Od-Erdene,NaN,mXJTJgfGbQRcLG,35.0,2024-07-26,35.0,2024-07-19,NaN,2024-07-05,2024-09-20,420.00,105.00,315.0,06a7e750-3aad-11ef-aa85-d2293387bbd7

In [8]:
df['STATUS'].unique()

array(['Cancelled', 'Active', 'Paused', 'Suspended', 'In Care',
       'In Transit'], dtype=object)

In [9]:
# Filter out rows where STATUS is 'Cancelled'
filtered_df = df[df['STATUS'] != 'Cancelled']
filtered_df

,AGREED_DATE,START_DATE,TYPE,STATUS,METHOD,CUSTOMER,REFERENCE,PAYMENT_REQUEST,NEXT_PAYMENT,NEXT_PAYMENT_ON,LAST_PAYMENT,LAST_PAYMENT_ON,CANCEL_DATE,COMMENCEMENT_DATE,COMPLETION_DATE,TOTAL_VALUE,PAID,REMAINING,AGREEMENT_ID
2,2022-04-19,2022-04-20,Recurring,Active,Visa,Michael Wawrzyniak,NaN,qcot98d2a4mg,220.0,2024-07-26,220.0,2024-07-19,NaN,2022-04-22,2024-10-04,28183.75,25763.75,2420.0,011bf6a4-7a39-46a6-8302-ee884114950c
13,2022-05-03,2022-05-03,Recurring,Active,Visa,Layne Hall,NaN,mrea1xj51a5v,35.0,2024-07-23,35.0,2024-07-16,NaN,2022-05-03,2024-10-01,4445.00,4060.00,385.0,000ae09c-6030-4929-b918-60225fab89b3
14,2022-05-06,2022-05-06,Recurring,Paused,Visa,Ben Fiechtner,NaN,kvzy2hkeay5c,35.0,2023-11-29,35.0,2023-11-22,NaN,2022-05-06,2024-03-06,2695.00,2170.00,525.0,66420089-e76d-4183-bbcd-be4f58f60df7
16,2022-05-08,2022-05-09,Recurring,Active,Mastercard,Sophia Fisher,NaN,o7dg6wa81ur6,166.0,2024-07-24,166.0,2024-07-10,NaN,2022-05-11,2024-12-11,11371.00,9545.00,1826.0,8d7fa6ac-de25-4909-b296-fd022f96f344
18,2022-05-08,2022-05-09,Recurring,Active,Mastercard,Kurt McCormick,NaN,kftz3frjatxm,35.0,2024-07-22,35.0,2024-07-15,NaN,2022-05-09,2024-09-30,4235.00,3850.00,385.0,2523fe4b-ddc6-499d-9999-0b0dbd91b181
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,2024-07-08,2024-07-08,Recurring,Active,Visa,Beth Perry,NaN,8n4XvfZ5Mz9QPa,35.0,2024-07-24,35.0,2024-07-17,NaN,2024-07-08,2024-10-02,455.00,70.00,385.0,1239d43e-3cbf-11ef-9499-967b370f99ea
306,2024-07-11,2024-07-09,Recurring,Active,Visa,Josh Wright,NaN,rkXqPiJsLTrSKc,35.0,2024-07-23,35.0,2024-07-16,NaN,2024-07-09,2024-10-01,455.00,70.00,385.0,05287186-3dc0-11ef-9b56-8620f1aa2c76
307,2024-07-12,2024-07-12,Recurring,Active,Mastercard,Kiel Woodward,NaN,2fV9ytFfRslJlb,99.0,2024-07-26,99.0,2024-07-12,NaN,2024-07-12,2024-12-13,1188.00,99.00,1089.0,d9112374-3f57-11ef-9e56-96d25c3b9f01
308,2024-07-16,2024-07-22,Recurring,In Transit,Visa,Bill Morrissey,NaN,nFypt6apxQr66f,35.0,2024-07-22,0.0,NaN,NaN,2024-07-22,2024-10-07,420.00,0.00,420.0,ba07ecde-4302-11ef-af32-4ebdaad81281
309,2024-07-19,2024-07-05,Recurring,Active,Mastercard,Usukhbayar Od-Erdene,NaN,mXJTJgfGbQRcLG,35.0,2024-07-26,35.0,2024-07-19,NaN,2024-07-05,2024-09-20,420.00,105.00,315.0,06a7e750-3aad-11ef-aa85-d2293387bbd7